function createhist(data1)
%CREATEFIGURE(data1)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 03-Apr-2018 21:08:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
histogram(data1,'Parent',axes1,'Normalization','probability',...
    'BinMethod','auto','NumBins',7);
h=histfit(data1(:),7,'kernel')
h(1).FaceColor = [0 0.45 0.74];
mn=mean(data1(:),'omitnan');
plot([mn mn],[0 1.1*max(h(1).YData)],'k','LineWidth', 3)
% Create ylabel
ylabel('Rate');

% Create xlabel
xlabel('Deflection, m');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'XGrid','on','YGrid','on');
