function plot_circles(XMatrix1, YMatrix1, ZMatrix1)
%CREATEFIGURE(XMatrix1, YMatrix1, ZMatrix1)
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data

%  Auto-generated by MATLAB on 03-Apr-2018 21:28:18

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot3
plot31 = plot3(XMatrix1,YMatrix1,ZMatrix1,'Parent',axes1,'LineWidth',3);
set(plot31(1),'DisplayName','Compensated','Color',[0 0 1]);
set(plot31(2),'DisplayName','Non-compensated','Color',[1 0 0]);
set(plot31(3),'DisplayName','Target','LineStyle','--','Color',[0 0 0]);

% Create zlabel
zlabel('Z,m');

% Create ylabel
ylabel('Y,m');

% Create xlabel
xlabel('X,m');

view(axes1,[-31.1 34]);
% box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northeast');

