function show_err(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Apr-2018 22:37:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','\epsilon in X direction','Color',[1 0 0]);
set(plot1(2),'DisplayName','\epsilon in Y direction',...
    'Color',[0 0.800000011920929 0]);
set(plot1(3),'DisplayName','\epsilon in Z direction','Color',[0 0 1]);

% Create ylabel
ylabel('\epsilon, m');

% Create xlabel
xlabel('\phi, deg ');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 360]);
% box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'XGrid','on','YGrid','on','XTick',[0 60 120 180 240 300 360]);
% Create legend
legend(axes1,'show');

